# ---------- BUILD STAGE ----------
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# ---------- RUNTIME STAGE ----------
FROM node:18-alpine

WORKDIR /app

# Copy only needed files
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app .

ENV NODE_ENV=production
EXPOSE 4000

CMD ["node", "index.js"]
